version: "3"
services:
    poll:
        build: ./poll
        restart: on-failure
        image: poll
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - redis
        ports:
            - "5000:80"
        networks:
            - poll-tier
    redis:
        image: redis
        restart: on-failure
        ports:
            - "6379:6379"
        networks:
            - back-tier
            - poll-tier
    result:
        build: ./result
        restart: on-failure
        environment:
            - CONNECTION_PORT=80
            - PG=postgresql://ethan:bendavid@db/postgres
        depends_on:
            - db
        image: result
        ports:
            - "5001:80"
        networks:
            - result-tier
    worker:
        build: ./worker
        restart: on-failure
        environment:
            - REDIS_HOST=redis
            - DATABASE=db
            - POSTGRES_USER=ethan
            - POSTGRES_PASSWORD=bendavid
            
        depends_on:
            - redis
            - db
        image: worker
        networks:
            - back-tier
    db:
        image: postgres
        restart: on-failure
        networks:
            - back-tier
            - result-tier
        environment:
            - POSTGRES_PASSWORD=bendavid
            - POSTGRES_USER=ethan
            - POSTGRES_DB=postgres
        volumes:
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
networks:
    poll-tier:
    result-tier:
    back-tier:

volumes:
    db-data:
        driver: local